### PR TITLE
Update registry client

### LINKED ISSUE #22: Support for private gcr registries
Hi
currently it is fails if container image is stored on the private gcr registry with the following error:

```
Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"cf21320d-1d33-4fc6-a6f5-65a550ed25ef\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot create client for registry: Get \\\"https://gcr.io/v2/\\\": http: non-successful response (status=401 body=\\\"{\\\\\\\"errors\\\\\\\":[{\\\\\\\"code\\\\\\\":\\\\\\\"UNAUTHORIZED\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"Unauthorized access.\\\\\\\"}]}\\\")\"}}}") has prevented the request from succeeding
```

it is impossible to solve this by providing registry credentials - as there is no static password, it should support gcr method of authentication

### LINKED ISSUE #24: Support for private aws ecr registries
Currently it is fails if image for container is from private aws ecr registry:
```
2021/07/13 15:18:36 registry.ping url=https://857306286857.dkr.ecr.eu-west-1.amazonaws.com/v2/
```

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes #22
Fixes #24
Fixes #31

### CODE REVIEW

**Comment by sagikazarmark** [comment]
The linter passes locally.

**Comment by gabomarf** [comment]
@sagikazarmark I closed my pull request that was a copy (theft of your code) and I'm really ashamed of what I did, I know that next time I should comment, I'm really sorry **and a lot thanks for you response and work**

**Comment by sagikazarmark** [comment]
No need to be ashames at all. You did nothing wrong, but it would have been more respectful if you talked to me first. No harm is done though, so don't feel bad!

**Comment by brtknr** [comment]
Neat! Thanks for fixing this, look forward to trying this against our private registry.

**Comment by brtknr** [comment]
I am still seeing the following error even with `0.4.3` version of the image:
```
  Warning  FailedCreate  65s                replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"a6d53ad6-a16e-4da4-948f-7589d959e04a\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
  Warning  FailedCreate  24s (x5 over 64s)  replicaset-controller  (combined from similar events): Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"41817a2d-9e0e-4ef1-88df-240a15031332\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
```

**Comment by sagikazarmark** [comment]
The change hasn't been released yet as far as I can tell.

**Comment by gabomarf** [comment]
> I am still seeing the following error even with `0.4.3` version of the image (although I noticed that the initContainerImage is still `0.4.2`) when I run `kubectl describe rs/rs-name`:
> 
> ```
>   Warning  FailedCreate  65s                replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"a6d53ad6-a16e-4da4-948f-7589d959e04a\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
>   Warning  FailedCreate  24s (x5 over 64s)  replicaset-controller  (combined from similar events): Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"41817a2d-9e0e-4ef1-88df-240a15031332\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
> ```
> 
> Am I missing something? Does the `kube-secrets-init` service account require a particular GCP IAM role?



> I am still seeing the following error even with `0.4.3` version of the image (although I noticed that the initContainerImage is still `0.4.2`) when I run `kubectl describe rs/rs-name`:
> 
> ```
>   Warning  FailedCreate  65s                replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"a6d53ad6-a16e-4da4-948f-7589d959e04a\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
>   Warning  FailedCreate  24s (x5 over 64s)  replicaset-controller  (combined from similar events): Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"41817a2d-9e0e-4ef1-88df-240a15031332\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
> ```
> 
> Am I missing something? Does the `kube-secrets-init` service account require a particular GCP IAM role?

Maybe we must report this how a issue

**Comment by gabomarf** [comment]
> I am still seeing the following error even with `0.4.3` version of the image (although I noticed that the initContainerImage is still `0.4.2`) when I run `kubectl describe rs/rs-name`:
> 
> ```
>   Warning  FailedCreate  65s                replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"a6d53ad6-a16e-4da4-948f-7589d959e04a\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
>   Warning  FailedCreate  24s (x5 over 64s)  replicaset-controller  (combined from similar events): Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"41817a2d-9e0e-4ef1-88df-240a15031332\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
> ```
> 
> Am I missing something? Does the `kube-secrets-init` service account require a particular GCP IAM role?

I solved this;

1.  I've created a secret. `kubectl -n my-namespace create secret docker-registry secrets-init-webhook-deployment \
 --docker-server="https://${DOCK_REG_XXX}" \
 --docker-username=${DOCK_REG_USER_XXX} \
 --docker-email=${DOCK_REG_EMAIL_XXX} \
 --docker-password="$(cat $DOCK_REG_PWD_XXX)" || true`

2. In the deployment.yaml I added:
`env:
            - name: DOCKER_CONFIG
              value: /opt/.docker
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-secret
              mountPath: /opt/.docker
              readOnly: true
      serviceAccountName: secrets-init-webhook-sa
      volumes:
        - name: webhook-certs
          secret:
            secretName: secrets-init-webhook-certs
        - name: webhook-secret
          secret:
            secretName: secrets-init-webhook-deployment
            items:
              - key: .dockerconfigjson
                path: config.json
`

**Comment by brtknr** [comment]
> > I am still seeing the following error even with `0.4.3` version of the image (although I noticed that the initContainerImage is still `0.4.2`) when I run `kubectl describe rs/rs-name`:
> > ```
> >   Warning  FailedCreate  65s                replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"a6d53ad6-a16e-4da4-948f-7589d959e04a\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
> >   Warning  FailedCreate  24s (x5 over 64s)  replicaset-controller  (combined from similar events): Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"41817a2d-9e0e-4ef1-88df-240a15031332\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot fetch image descriptor: GET https://eu.gcr.io/v2/tillit-api/njord-bank/manifests/sha-508ebe3: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\"}}}") has prevented the request from succeeding
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am I missing something? Does the `kube-secrets-init` service account require a particular GCP IAM role?
> 
> @sagikazarmark [brtknr](https://github.com/brtknr) I solved that with this;
> 
> 1. I've created a secret. `kubectl -n my-namespace create secret docker-registry secrets-init-webhook-deployment \  --docker-server="https://${DOCK_REG_XXX}" \  --docker-username=${DOCK_REG_USER_XXX} \  --docker-email=${DOCK_REG_EMAIL_XXX} \  --docker-password="$(cat $DOCK_REG_PWD_XXX)" || true`
> 2. In the deployment.yaml I added:
>    `env: - name: DOCKER_CONFIG value: /opt/.docker volumeMounts: - name: webhook-certs mountPath: /etc/webhook/certs readOnly: true - name: webhook-secret mountPath: /opt/.docker readOnly: true serviceAccountName: secrets-init-webhook-sa volumes: - name: webhook-certs secret: secretName: secrets-init-webhook-certs - name: webhook-secret secret: secretName: secrets-init-webhook-deployment items: - key: .dockerconfigjson path: config.json`

That’s a hack, not a proper fix which is what I was hoping this PR would be. The previous hack of explicitly defining the entry point seems preferable to this solition

**Comment by sagikazarmark** [comment]
@brtknr depending on how your GKE cluster is running you need to give read access to the relevant GCS bucket to the IAM service account your workload is running with:

- If Workload Identity is enabled, create an IAM service account for kube-secrets-init, annotate the kube service account so that it runs with the right IAM credentials.
- If Workload Identity is disabled, your workload will use the cluster IAM service account.

You need to grant read access to the right IAM service account for kube-secrets-init to work.

> The previous hack of explicitly defining the entry point seems preferable to this solition

That's not actually a hack, it's how you can avoid kube-secrets-init trying to figure out the entrypoint from the image.

**Comment by brtkwr** [comment]
@sagikazarmark I just saw that you responded to my message. I was just revisiting this and I managed to solve this by granting the workload identity for kube-secrets-init serviceaccount use by the workload on GKE roles/artifactregistry.reader role at project level.

**Pull request merged**
