### PR TITLE
Fix default image pull secret flags

### LINKED ISSUE #9: Google Cloud image pull secret
I'm trying to use the webhook on google cloud, but I can't seem to be able to authenticate against GCR. There was an issue about it: #1, but it was closed without a resolution.

GCR uses service account keys for authentication, which is a JSON payload and it doesn't seem to work with neither password nor "auth" (using auth field from the docker config) authentication.

Am I missing something? Is there a solution already? Thanks!

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes #9

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Ping @alexei-led

**Comment by sagikazarmark** [comment]
Ping @alexei-led

**Comment by sagikazarmark** [comment]
Hey @alexei-led ,

Can you take a look at this PR? It fixes a major bug in my opinion.

Thanks!

**Comment by alexei-led** [comment]
@sagikazarmark thank you for PR

**Comment by sagikazarmark** [comment]
Thanks for merging @alexei-led 

Can you tag a new release with this fix?

**Pull request merged**
